const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={score:document.querySelector('#score'),best:document.querySelector('#best'),start:document.querySelector('#startPanel'),over:document.querySelector('#gameOver'),overBanner:document.querySelector('#gameOverBanner'),pause:document.querySelector('#pausePanel'),pauseBtn:document.querySelector('#pauseBtn'),final:document.querySelector('#finalScore'),note:document.querySelector('#newBest'),toast:document.querySelector('#toast'),scoreWrap:document.querySelector('.score-wrap')};
let W,H,dpr,mode='intro',last=0,score=0,best=+localStorage.forestBest||0,muted=false;
let bird={x:0,y:0,vy:0,r:34,rot:0},obstacles=[],powerups=[],nectar=[],particles=[],far=0,near=0,spawn=0,shake=0,audio,shield=0,boost=0,magnet=0,invuln=0,musicStep=0,musicNext=0,musicSection=0,scene=0,oldScene=0,sceneMix=1,nextSceneScore=22,restartUnlock=0,lastCheer=0;
const birdImg=new Image(),birdSprite=document.createElement('canvas');
const bgImgs=['assets/forest-loop-bg.png','assets/forest-sunset-loop.png','assets/forest-night-loop.png','assets/forest-sakura-loop.png','assets/forest-rain-loop.png','assets/forest-autumn-loop.png','assets/forest-snow-loop.png'].map(src=>{let img=new Image();img.src=src;return img});
birdImg.src='assets/peachy-bird-v6-source.png';
birdImg.onload=()=>{const w=birdImg.width,h=birdImg.height,c=birdSprite.getContext('2d',{willReadFrequently:true});birdSprite.width=w;birdSprite.height=h;c.drawImage(birdImg,0,0);let im=c.getImageData(0,0,w,h),d=im.data,seen=new Uint8Array(w*h),q=new Int32Array(w*h),head=0,tail=0;q[tail++]=0;seen[0]=1;while(head<tail){let p=q[head++],i=p*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);if(mx-mn>16)continue;d[i+3]=0;let x=p%w,y=(p/w)|0,n;if(x&& !seen[n=p-1])seen[n]=1,q[tail++]=n;if(x<w-1&&!seen[n=p+1])seen[n]=1,q[tail++]=n;if(y&&!seen[n=p-w])seen[n]=1,q[tail++]=n;if(y<h-1&&!seen[n=p+w])seen[n]=1,q[tail++]=n}c.putImageData(im,0,0)};ui.best.textContent=best;
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);bird.r=Math.max(27,Math.min(40,W*.035));if(mode==='intro'){bird.x=Math.min(W*.29,320);bird.y=H*.48}}
addEventListener('resize',resize);resize();
const rand=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function tone(freq,duration=.07,type='sine',gain=.04){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
const musicSections=[
 [659,784,880,784,659,587,523,587,659,784,1047,880,784,659,587,523],
 [784,880,988,1047,988,880,784,659,698,784,880,784,698,659,587,659],
 [523,659,784,659,587,698,880,698,659,784,988,1175,1047,880,784,659],
 [880,784,698,659,587,659,698,784,1047,988,880,784,698,784,659,587]
],chordRoots=[262,220,175,196,262,175,196,220];
function musicNote(freq,when,duration,gain,type='triangle'){if(!audio||muted)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,when);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(gain,when+.018);g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g).connect(audio.destination);o.start(when);o.stop(when+duration+.02)}
function startMusic(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();musicNext=audio.currentTime+.06}catch{}}
function scheduleMusic(){if(!audio||muted||mode==='paused'||audio.state!=='running')return;if(!musicNext||musicNext<audio.currentTime)musicNext=audio.currentTime+.04;while(musicNext<audio.currentTime+.18){let absolute=musicStep++,step=absolute%16,quiet=mode!=='playing';if(step===0){let choices=scene===2?[1,2,3]:scene===1?[0,1,3]:[0,1,2,3],next=choices[(Math.random()*choices.length)|0];musicSection=next===musicSection?choices[(choices.indexOf(next)+1)%choices.length]:next}let section=mode==='intro'?2:mode==='over'?1:musicSection,f=musicSections[section][step],root=chordRoots[(Math.floor(absolute/4)+scene)%chordRoots.length],beat=(quiet?.235:.205)+Math.sin(absolute*.47)*.006,gain=quiet?.009:.013;if(step%8===7&&section%2)f*=.5;let rest=mode==='playing'&&Math.random()<.055&&step%4!==0;if(!rest){musicNote(f,musicNext,step%4===3?.3:.19,gain,scene===2?'sine':'triangle');if(step%2===0)musicNote(f*2,musicNext+.02,.08,.003,'sine')}if(step%4===0){musicNote(root,musicNext,.42,.007,'sine');musicNote(root*1.5,musicNext+.025,.3,.003,'triangle')}if(Math.random()<.24)musicNote(scene===2?1175:1568,musicNext+.105,.06,.0022,'sine');if(step===14&&Math.random()<.45)musicNote(f*1.5,musicNext+.1,.16,.0035,'triangle');musicNext+=beat}}
function reset(){score=0;lastCheer=0;shield=0;boost=0;magnet=0;invuln=0;scene=oldScene=0;sceneMix=1;nextSceneScore=Math.floor(rand(18,29));ui.score.textContent=0;obstacles=[];powerups=[];nectar=[];particles=[];bird.x=Math.min(W*.28,310);bird.y=H*.43;bird.vy=-1.5;bird.rot=0;spawn=56;shake=0;mode='playing';musicStep=0;startMusic();updatePowerUI();ui.start.classList.add('hidden');ui.over.classList.add('hidden');ui.pause.classList.add('hidden');ui.overBanner.classList.remove('show');ui.pauseBtn.classList.remove('hidden-control')}
function maybeChangeScene(){if(score<nextSceneScore)return;oldScene=scene;let options=bgImgs.map((_,i)=>i).filter(v=>v!==scene);scene=options[(Math.random()*options.length)|0];sceneMix=0;nextSceneScore=score+Math.floor(rand(22,39))}
function flap(){if(mode==='intro')reset();else if(mode==='over'){if(performance.now()<restartUnlock)return;reset()}if(mode==='playing'){let snowy=scene===6&&sceneMix>.85;bird.vy=snowy?-5.72:-6.15;tone(snowy?480:520,.055,'sine',.025);for(let i=0;i<7;i++)particles.push({x:bird.x-24,y:bird.y+rand(-12,12),vx:rand(-2.8,-.8),vy:rand(-1.4,1.4),life:1,s:rand(2,6),c:i%2?'#fff4b5':'#f7a5bd'})}}
document.querySelector('#startBtn').onclick=e=>{e.stopPropagation();reset()};document.querySelector('#restartBtn').onclick=e=>{e.stopPropagation();if(performance.now()>=restartUnlock)reset()};
document.querySelector('.sound').onclick=e=>{e.stopPropagation();muted=!muted;e.currentTarget.classList.toggle('muted',muted);e.currentTarget.setAttribute('aria-label',muted?'打开声音':'关闭声音');if(!muted)startMusic()};
addEventListener('pointerdown',startMusic,{once:true,capture:true});addEventListener('keydown',startMusic,{once:true,capture:true});startMusic();
function togglePause(){if(mode==='playing'){mode='paused';ui.pause.classList.remove('hidden');ui.pauseBtn.textContent='▶'}else if(mode==='paused'){mode='playing';last=performance.now();ui.pause.classList.add('hidden');ui.pauseBtn.textContent='Ⅱ'}}
ui.pauseBtn.onclick=e=>{e.stopPropagation();togglePause()};document.querySelector('#resumeBtn').onclick=e=>{e.stopPropagation();togglePause()};
canvas.addEventListener('pointerdown',flap);addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();flap()}});
addEventListener('keydown',e=>{if(e.code==='KeyP'||e.code==='Escape')togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')togglePause()});
function addObstacle(){let gap=clamp(H*.28-score*.85,168,240),margin=Math.max(115,H*.16),center=rand(margin+gap/2,H-margin-gap/2),w=clamp(W*.085,72,104),x=W+80,type='meadow';if(score>=6&&Math.random()<.45)type='blossom';if(score>=11&&Math.random()<.32)type='sway';if(score>=18&&Math.random()<.28)type='ancient';let top=center-gap/2,bottom=center+gap/2,seed=Math.random()*99;obstacles.push({x,w,top,bottom,baseTop:top,baseBottom:bottom,passed:false,seed,type});if(Math.random()<.42){let count=2+((Math.random()*3)|0),nx=x+w+rand(80,125);for(let i=0;i<count;i++){nx+=rand(52,94);nectar.push({x:nx,y:center+rand(-Math.min(48,gap*.25),Math.min(48,gap*.25)),phase:Math.random()*6.28,taken:false})}}if(score>0&&Math.random()<.34&&!powerups.length){let roll=Math.random(),pickup=roll<.43?'shield':roll<.72?'boost':'magnet';powerups.push({x:x+w+105,y:center+rand(-gap*.22,gap*.22),type:pickup,phase:Math.random()*6.28,taken:false})}}
function leaf(x,y,ang,s=1){ctx.save();ctx.translate(x,y);ctx.rotate(ang);ctx.fillStyle='#8bcf55';ctx.strokeStyle='#426d36';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(0,0);ctx.bezierCurveTo(9*s,-19*s,30*s,-18*s,36*s,0);ctx.bezierCurveTo(24*s,17*s,8*s,14*s,0,0);ctx.fill();ctx.stroke();ctx.strokeStyle='rgba(227,248,139,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(4*s,0);ctx.quadraticCurveTo(19*s,-2*s,31*s,0);ctx.stroke();ctx.restore()}
function flower(x,y,s=1){ctx.save();ctx.translate(x,y);ctx.fillStyle='#fff8d3';ctx.strokeStyle='#9b925c';ctx.lineWidth=1.2;for(let i=0;i<5;i++){ctx.rotate(Math.PI*2/5);ctx.beginPath();ctx.ellipse(0,-7*s,4*s,8*s,0,0,7);ctx.fill();ctx.stroke()}ctx.fillStyle='#edc458';ctx.beginPath();ctx.arc(0,0,3.5*s,0,7);ctx.fill();ctx.restore()}
function vine(x,y,len,flip,seed,type='meadow'){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(1,-1);let palettes={meadow:['#355d31','#60933e','#91c753'],blossom:['#5e6530','#9eaa45','#d2ce65'],sway:['#315d51','#4d9172','#8bc99a'],ancient:['#29452b','#456b38','#789843']},pal=palettes[type],sway=Math.sin(seed)*9;ctx.lineCap='round';ctx.strokeStyle=pal[0];ctx.lineWidth=type==='ancient'?34:30;ctx.beginPath();ctx.moveTo(3,-20);ctx.bezierCurveTo(-22+sway,len*.28,22+sway,len*.64,2,len-21);ctx.stroke();ctx.strokeStyle=pal[1];ctx.lineWidth=type==='ancient'?26:23;ctx.stroke();ctx.strokeStyle=pal[2];ctx.lineWidth=8;ctx.globalAlpha=.85;ctx.beginPath();ctx.moveTo(-2,-15);ctx.bezierCurveTo(-17+sway,len*.28,14+sway,len*.63,-4,len-25);ctx.stroke();ctx.globalAlpha=1;for(let yy=55;yy<len-60;yy+=78){let side=((yy/78+seed)|0)%2?1:-1,px=4+Math.sin(yy*.04+seed)*13;leaf(px+side*8,yy,side*(.25+Math.PI*(side<0)),type==='ancient'?1.02:.78+((yy+seed)%20)/80);let flowerChance=Math.sin(seed*2.7+yy*.81);if((type==='blossom'&&flowerChance>.25)||(type!=='blossom'&&flowerChance>.78))flower(px-side*18,yy+12,type==='blossom'?.9:.7);if(type==='ancient'){ctx.save();ctx.translate(px-side*11,yy+23);ctx.rotate(side*.5);ctx.fillStyle='#d7b96a';ctx.strokeStyle=pal[0];ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(side*15,6);ctx.lineTo(2,11);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}}let tipY=len-21;ctx.strokeStyle=pal[0];ctx.lineWidth=15;ctx.beginPath();ctx.moveTo(2,tipY);ctx.bezierCurveTo(40,tipY+8,47,tipY-40,20,tipY-47);ctx.bezierCurveTo(-2,tipY-53,-6,tipY-27,11,tipY-24);ctx.stroke();ctx.strokeStyle=pal[2];ctx.lineWidth=9;ctx.stroke();leaf(-2,len-49,-2.75,1.05);leaf(12,len-58,-.38,.92);if(type==='blossom'&&Math.sin(seed)>-.1)flower(34,len-34,1);ctx.restore()}
function cloud(x,y,s,a=.7){ctx.save();ctx.globalAlpha=a;ctx.fillStyle='#fffde7';ctx.beginPath();ctx.ellipse(x,y,64*s,24*s,0,0,7);ctx.ellipse(x+35*s,y-16*s,43*s,34*s,0,0,7);ctx.ellipse(x-34*s,y-10*s,38*s,29*s,0,0,7);ctx.fill();ctx.restore()}
function leafBlob(x,y,s,c){ctx.fillStyle=c;ctx.beginPath();for(let i=0;i<10;i++){let a=i/10*Math.PI*2,r=s*(.72+.2*Math.sin(i*4.3));let px=x+Math.cos(a)*r,py=y+Math.sin(a)*r*.63;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill()}
function drawBgLayer(img,alpha){if(!img.complete||!img.naturalWidth)return;let tileH=H,tileW=tileH*img.naturalWidth/img.naturalHeight,offset=(far*.22)%(tileW*2),start=-offset-tileW;ctx.save();ctx.globalAlpha=alpha;for(let i=-1;i<Math.ceil(W/tileW)+3;i++){let x=start+i*tileW,flip=Math.abs(i)%2===1;ctx.save();if(flip){ctx.translate(x+tileW,0);ctx.scale(-1,1);ctx.drawImage(img,0,0,tileW+1,tileH)}else ctx.drawImage(img,x,0,tileW+1,tileH);ctx.restore()}ctx.restore()}
function background(t){ctx.fillStyle=scene===2?'#276078':'#cbe890';ctx.fillRect(0,0,W,H);if(sceneMix<1)drawBgLayer(bgImgs[oldScene],1-sceneMix);drawBgLayer(bgImgs[scene],sceneMix);let haze=ctx.createLinearGradient(0,0,0,H);haze.addColorStop(0,scene===2?'rgba(80,140,190,.08)':'rgba(230,250,203,.06)');haze.addColorStop(.5,'rgba(255,250,191,.07)');haze.addColorStop(1,'rgba(75,130,67,.06)');ctx.fillStyle=haze;ctx.fillRect(0,0,W,H)}
function drawBird(t){ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.rot);let bob=mode==='intro'?Math.sin(t*.003)*8:0,s=bird.r*2.9;ctx.translate(0,bob);if(boost>0){ctx.globalAlpha=.32;for(let i=1;i<=4;i++){ctx.fillStyle=i%2?'#ffe16c':'#fff7bd';ctx.beginPath();ctx.ellipse(-s*.5-i*18,Math.sin(t*.01+i)*7,22+i*4,4,0,0,7);ctx.fill()}ctx.globalAlpha=1}ctx.shadowColor='rgba(72,70,39,.22)';ctx.shadowBlur=15;ctx.shadowOffsetY=8;if(birdSprite.width)ctx.drawImage(birdSprite,-s*.57,-s*.48,s*1.14,s*.96);else{ctx.fillStyle='#f8a8c5';ctx.beginPath();ctx.arc(0,0,bird.r,0,7);ctx.fill()}if(shield){ctx.shadowBlur=0;let pulse=2+Math.sin(t*.008)*2,g=ctx.createRadialGradient(-8,-10,10,0,0,bird.r*1.45+pulse);g.addColorStop(.65,'rgba(130,236,255,.05)');g.addColorStop(1,'rgba(82,190,235,.36)');ctx.fillStyle=g;ctx.strokeStyle='rgba(220,255,255,.9)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,bird.r*1.4+pulse,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-bird.r*.7,-bird.r*.8,4,0,7);ctx.fill()}ctx.restore()}
function drawPowerup(p,t){let y=p.y+Math.sin(t*.005+p.phase)*9;ctx.save();ctx.translate(p.x,y);let pulse=1+Math.sin(t*.007+p.phase)*.07;ctx.scale(pulse,pulse);ctx.shadowColor=p.type==='shield'?'#67d9ed':p.type==='magnet'?'#ff98bd':'#ffd34e';ctx.shadowBlur=20;if(p.type==='shield'){let g=ctx.createRadialGradient(-6,-7,3,0,0,24);g.addColorStop(0,'#efffff');g.addColorStop(.45,'#85e4f3');g.addColorStop(1,'#4caecf');ctx.fillStyle=g;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,21,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='rgba(255,255,255,.9)';ctx.beginPath();ctx.arc(-7,-8,5,0,7);ctx.fill()}else if(p.type==='magnet'){ctx.shadowBlur=13;ctx.lineCap='round';ctx.strokeStyle='#62463d';ctx.lineWidth=20;ctx.beginPath();ctx.arc(0,-1,18,.08,Math.PI-.08,true);ctx.stroke();let mg=ctx.createLinearGradient(-20,-20,20,18);mg.addColorStop(0,'#ffb7cf');mg.addColorStop(.5,'#ef7fa8');mg.addColorStop(1,'#d95f91');ctx.strokeStyle=mg;ctx.lineWidth=13;ctx.stroke();ctx.fillStyle='#fff0a5';ctx.strokeStyle='#62463d';ctx.lineWidth=3;for(let x of[-18,18]){ctx.beginPath();ctx.roundRect(x-7,7,14,13,5);ctx.fill();ctx.stroke()}ctx.fillStyle='#fff';ctx.globalAlpha=.9;ctx.beginPath();ctx.arc(-10,-14,3,0,7);ctx.fill();ctx.globalAlpha=.8;for(let [sx,sy,ss] of [[-27,-18,3],[27,-9,2]]){ctx.save();ctx.translate(sx,sy);ctx.rotate(Math.PI/4);ctx.fillStyle='#fff7b3';ctx.fillRect(-ss,-ss,ss*2,ss*2);ctx.restore()}}else{ctx.rotate(-.35);ctx.fillStyle='#ffe45d';ctx.strokeStyle='#8d642b';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-22,15);ctx.quadraticCurveTo(-7,-25,20,-17);ctx.quadraticCurveTo(11,8,-22,15);ctx.fill();ctx.stroke();ctx.strokeStyle='#fff5ad';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-15,10);ctx.lineTo(11,-11);ctx.stroke()}ctx.restore()}
function drawNectar(n,t){let y=n.y+Math.sin(t*.006+n.phase)*6;ctx.save();ctx.translate(n.x,y);ctx.rotate(t*.001+n.phase);ctx.shadowColor='#fff3a0';ctx.shadowBlur=14;ctx.fillStyle='#fff9c9';for(let i=0;i<5;i++){ctx.rotate(Math.PI*2/5);ctx.beginPath();ctx.ellipse(0,-7,3.5,7,0,0,7);ctx.fill()}ctx.fillStyle='#f5bd4b';ctx.beginPath();ctx.arc(0,0,3.5,0,7);ctx.fill();ctx.restore()}
function drawVisitor(t){if(!visitor)return;ctx.save();ctx.translate(visitor.x,visitor.y+Math.sin(t*.009+visitor.phase)*8);if(visitor.type==='butterfly'){let flap=.45+Math.abs(Math.sin(t*.025))*1.05;ctx.strokeStyle='#6c553b';ctx.lineWidth=2;ctx.fillStyle='#f6a6c5';ctx.beginPath();ctx.ellipse(-7,0,11,17,-flap*.35,0,7);ctx.ellipse(7,0,11,17,flap*.35,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#ffe36b';ctx.beginPath();ctx.ellipse(0,3,3,10,0,0,7);ctx.fill()}else{ctx.shadowColor='#fff39b';ctx.shadowBlur=22;ctx.fillStyle='#ffe86f';ctx.beginPath();ctx.arc(0,0,7,0,7);ctx.fill();ctx.fillStyle='rgba(220,249,255,.75)';ctx.beginPath();ctx.ellipse(-8,-3,8,4,-.4,0,7);ctx.ellipse(8,-3,8,4,.4,0,7);ctx.fill()}ctx.restore()}
function end(){if(mode!=='playing')return;mode='dying';shake=9;tone(120,.22,'sawtooth',.04);ui.pauseBtn.classList.add('hidden-control');ui.final.textContent=score;let restartBtn=document.querySelector('#restartBtn');restartBtn.disabled=true;restartBtn.classList.add('hidden-control');let isBest=score>best;if(isBest){best=score;localStorage.forestBest=best;ui.best.textContent=best}ui.note.textContent=isBest?'新的最佳旅程！森林记住你啦 ✦':'再试一次，会飞得更远喔';ui.overBanner.classList.remove('show');void ui.overBanner.offsetWidth;ui.overBanner.classList.add('show');setTimeout(()=>{mode='over';ui.over.classList.remove('hidden');restartUnlock=performance.now()+700;setTimeout(()=>{restartBtn.disabled=false;restartBtn.classList.remove('hidden-control')},700)},850)}
function encourage(){let tier=Math.floor(score/100);if(!tier||tier<=lastCheer)return;lastCheer=tier;let cheers=['太厉害啦！继续向森林深处飞！','肥丸又飞过一百片星光啦！','森林里的朋友都在为你加油！','好稳！下一段风景也在等你！'];ui.toast.textContent=cheers[(tier-1)%cheers.length];ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show');tone(1047,.16,'triangle',.04);setTimeout(()=>tone(1318,.16,'triangle',.035),90)}
function celebrate(){tone(760,.1,'sine',.035);ui.scoreWrap.classList.remove('pop');void ui.scoreWrap.offsetWidth;ui.scoreWrap.classList.add('pop');encourage();for(let i=0;i<12;i++)particles.push({x:bird.x+30,y:bird.y+rand(-24,24),vx:rand(-2,2),vy:rand(-2.4,2.4),life:1,s:rand(3,7),c:i%3===0?'#ffd967':i%3===1?'#fff8cf':'#8ad47f'})}
function updatePowerUI(){}
function collect(p){p.taken=true;if(p.type==='shield'){shield=1;tone(620,.16,'sine',.05);setTimeout(()=>tone(850,.12,'sine',.035),60);ui.toast.textContent='◉ 获得森林护盾'}else if(p.type==='magnet'){magnet=360;tone(720,.18,'sine',.045);ui.toast.textContent='∩ 花蜜自动吸附'}else{boost=260;invuln=Math.max(invuln,260);tone(880,.18,'triangle',.05);ui.toast.textContent='➤ 疾风飞行！'}ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show');for(let i=0;i<18;i++)particles.push({x:p.x,y:p.y,vx:rand(-3,3),vy:rand(-3,3),life:1,s:rand(3,8),c:p.type==='shield'?'#91ecf5':p.type==='magnet'?'#ffb1cc':'#ffe76f'});updatePowerUI()}
function collectNectar(n){n.taken=true;score++;maybeChangeScene();encourage();ui.score.textContent=score;tone(900+score%3*120,.07,'sine',.025);ui.scoreWrap.classList.remove('pop');void ui.scoreWrap.offsetWidth;ui.scoreWrap.classList.add('pop');for(let i=0;i<7;i++)particles.push({x:n.x,y:n.y,vx:rand(-2,2),vy:rand(-2,2),life:1,s:rand(2,5),c:'#fff2a0'})}
function absorbHit(){shield=0;invuln=95;shake=5;tone(250,.14,'sine',.04);ui.toast.textContent='护盾挡住了一次碰撞';ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show');updatePowerUI()}
function update(dt){if(shake>.05)shake*=Math.pow(.8,dt);else shake=0;if(sceneMix<1&&mode!=='paused')sceneMix=Math.min(1,sceneMix+.008*dt);if(mode!=='paused'){far+=dt*(boost>0?1.7:1);near+=dt}if(mode!=='playing')return;if(boost>0){boost=Math.max(0,boost-dt);if(boost===0)invuln=0;updatePowerUI()}if(magnet>0){magnet=Math.max(0,magnet-dt);updatePowerUI()}bird.vy+=.305*dt;if(invuln>0)invuln=Math.max(0,invuln-dt);bird.y+=bird.vy*dt;bird.rot=clamp(bird.vy*.05,-.32,.68);spawn-=dt;if(spawn<=0){addObstacle();spawn=clamp(108-score*.28-W*.006,80,104)}let speed=Math.min(4.15,3.02+score*.026+Math.floor(score/8)*.055)+(boost>0?3.4:0);for(let o of obstacles){o.x-=speed*dt;if(o.type==='sway'){let shift=Math.sin(far*.018+o.seed)*18;o.top=o.baseTop+shift;o.bottom=o.baseBottom+shift}let hitX=bird.x+bird.r*.5>o.x&&bird.x-bird.r*.5<o.x+o.w,hitY=bird.y-bird.r*.47<o.top||bird.y+bird.r*.47>o.bottom,clearance=Math.min(bird.y-bird.r*.47-o.top,o.bottom-bird.y-bird.r*.47);if(hitX&&!hitY&&clearance>0&&clearance<20)o.grazed=true;if(!o.passed&&o.x+o.w*.5<bird.x){o.passed=true;score++;if(o.grazed&&!boost){score+=2;ui.toast.textContent='漂亮擦边 +2';ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show');tone(1120,.1,'triangle',.035);for(let i=0;i<14;i++)particles.push({x:bird.x,y:bird.y,vx:rand(-2,1),vy:rand(-2.5,2.5),life:1,s:rand(2,5),c:'#a7f1d0'})}maybeChangeScene();ui.score.textContent=score;celebrate()}if(hitX&&hitY&&!invuln){if(shield)absorbHit();else end()}}for(let p of powerups){p.x-=speed*dt;if(!p.taken&&Math.hypot(p.x-bird.x,p.y-bird.y)<bird.r+22)collect(p)}for(let n of nectar){n.x-=speed*dt;let dx=bird.x-n.x,dy=bird.y-n.y,dist=Math.hypot(dx,dy);if(magnet>0&&!n.taken&&dist<250){if(dist<145||n.x<bird.x-8){collectNectar(n);continue}let pull=(1-dist/250)*.11+.035;n.x+=dx*pull*dt;n.y+=dy*pull*dt}if(!n.taken&&Math.hypot(n.x-bird.x,n.y-bird.y)<bird.r+14)collectNectar(n)}obstacles=obstacles.filter(o=>o.x>-150);powerups=powerups.filter(p=>p.x>-80&&!p.taken);nectar=nectar.filter(n=>n.x>-50&&!n.taken);if((bird.y<-45||bird.y>H+38)&&!invuln)end();else if(boost>0)bird.y=clamp(bird.y,45,H-45);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.015*dt;p.life-=.023*dt});particles=particles.filter(p=>p.life>0)}
function drawSnow(t){if(scene!==6||sceneMix<.25)return;ctx.save();ctx.globalAlpha=Math.min(.72,sceneMix*.72);ctx.fillStyle='#fff';for(let i=0;i<34;i++){let x=(i*127+t*.025*(1+i%3))%(W+80)-40,y=(i*83+t*.045*(1+i%2))%(H+70)-35,r=1.5+i%4*.65;ctx.beginPath();ctx.arc(x+Math.sin(t*.001+i)*18,y,r,0,7);ctx.fill()}ctx.restore()}
function draw(t){ctx.save();if(shake>0)ctx.translate(rand(-shake,shake),rand(-shake,shake));background(t);drawSnow(t);for(let o of obstacles){vine(o.x+o.w/2,0,o.top,false,o.seed,o.type);vine(o.x+o.w/2,H,H-o.bottom,true,o.seed+3,o.type)}for(let n of nectar)if(!n.taken)drawNectar(n,t);for(let p of powerups)if(!p.taken)drawPowerup(p,t);for(let p of particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.s*p.life,0,7);ctx.fill()}ctx.globalAlpha=1;drawBird(t);ctx.restore()}
function loop(t){let dt=Math.min((t-last)/16.67||1,2);last=t;update(dt);scheduleMusic();draw(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
